---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(shiny)
library(tidyverse)
library(rio)
library(modeldata)
library(plotly)
library(DT)
faersdata <- read_delim("DRUG_ADVERSE_REACTIONS_COUNT.txt", 
    delim = "$", escape_double = FALSE, trim_ws = TRUE)
faers_adrs <- faers_adrs <- faersdata %>% 
  arrange(DRUG) %>%
  filter(count_of_reaction > 500) %>% 
  drop_na()

faers_adrs$count_of_reaction <- as.numeric(faers_adrs$count_of_reaction)
faers_adrs$Adverse_Event <- as.factor(faers_adrs$Adverse_Event)
faers_adrs$DRUG <- as.factor(faers_adrs$DRUG)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
dv1 <- faers_adrs %>% 
      filter(DRUG %in% faers_adrs$DRUG) %>%
      ggplot(aes(x=Adverse_Event,y=count_of_reaction,width=.5))+
      geom_bar(stat='identity')+
      #coord_flip()+
      scale_x_discrete(expand=c(0,0))+
      scale_y_continuous(expand=c(0,0))+
      theme(panel.background = element_rect(fill = "white"),
            panel.grid.major.x = element_line(color = "#A8BAC4", size = 0.3),
            axis.ticks.length = unit(0, "mm"),
            axis.title = element_blank(),
            axis.line.y.left = element_line(color = "black"),
            axis.text.y = element_text(family = "sans", size = 8),
            axis.text.x = element_text(family = "sans", size =10, angle = 90))

ggplotly(dv1)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
faers_adrs %>% 
      filter(DRUG %in% faers_adrs$DRUG) %>%
      ggplot(aes(x=Adverse_Event,y=count_of_reaction,width=.5))+
      geom_bar(stat='identity')+
      #coord_flip()+
      scale_x_discrete(expand=c(0,0))+
      scale_y_continuous(expand=c(0,0))+
      theme(panel.background = element_rect(fill = "white"),
            panel.grid.major.x = element_line(color = "#A8BAC4", size = 0.3),
            axis.ticks.length = unit(0, "mm"),
            axis.title = element_blank(),
            axis.line.y.left = element_line(color = "black"),
            axis.text.y = element_text(family = "sans", size = 8),
            axis.text.x = element_text(family = "sans", size =10, angle = 90))

```

### Chart C

```{r}
datatable(faers_adrs,options = list(pageLength=1000))
```

